# Generated by Django 5.1.15 on 2026-06-30 08:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0005_eventslugalias'),
        ('orgs', '0002_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGateMinuteMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket_start', models.DateTimeField()),
                ('gate', models.CharField(blank=True, default='', max_length=64)),
                ('scanner', models.CharField(blank=True, default='', max_length=64)),
                ('checkins', models.PositiveIntegerField(default=0)),
                ('duplicates', models.PositiveIntegerField(default=0)),
                ('conflicts', models.PositiveIntegerField(default=0)),
                ('escalations', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_metrics', to='events.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orgs.organization')),
            ],
            options={
                'ordering': ('-bucket_start', 'gate', 'scanner'),
                'indexes': [models.Index(fields=['event', '-bucket_start'], name='metric_event_time_idx'), models.Index(fields=['event', 'gate', '-bucket_start'], name='metric_gate_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'bucket_start', 'gate', 'scanner'), name='unique_gate_metric_bucket')],
            },
        ),
    ]
