# Generated by Django 5.1.15 on 2026-05-20 13:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_registrationfield'),
        ('guests', '0001_initial'),
        ('orgs', '0002_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('self_serve', 'Self-serve')], max_length=16)),
                ('template', models.CharField(max_length=64)),
                ('recipient', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='queued', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.event')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='guests.guest')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orgs.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
