# Generated by Django 5.1.15 on 2026-05-22 07:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_walkin_displayed_unique'),
        ('notifications', '0001_initial'),
        ('orgs', '0002_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('bound_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_binding', to='guests.guest')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orgs.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['chat_id'], name='notificatio_chat_id_f389aa_idx')],
            },
        ),
    ]
