"""Storage selector for externally-served uploads (e.g. event banners).

Returns the `media_public` S3 (Tigris) storage when configured (prod/staging),
else the default local filesystem storage (dev/test). Used as a callable
`storage=` on ImageFields so the chosen backend is resolved at runtime, not
baked into migrations.

Note: Tigris does not serve objects publicly via S3 ACLs and only supports
whole-bucket public access, so `media_public` serves objects via short-lived
presigned GET URLs (querystring_auth=True) rather than stable public URLs. The
URL is regenerated by the serializer on each fetch.
"""

from __future__ import annotations

from django.conf import settings
from django.core.files.storage import FileSystemStorage, storages


def public_media_storage():
    if "media_public" in getattr(settings, "STORAGES", {}):
        return storages["media_public"]
    return FileSystemStorage()
