# Generated by Django 5.1.15 on 2026-05-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
