# Generated by Django 5.1.15 on 2026-05-20 13:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0002_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('live', 'Live'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Phnom_Penh', max_length=64)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('registration_open', models.BooleanField(default=True)),
                ('walkins_enabled', models.BooleanField(default=True)),
                ('event_pin_hash', models.CharField(blank=True, max_length=128)),
                ('event_pin_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orgs.organization')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'status'], name='events_even_organiz_a2ef24_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'slug'), name='unique_event_slug_per_org')],
            },
        ),
    ]
