# Generated by Django 5.1.15 on 2026-05-20 13:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.SlugField(max_length=40)),
                ('label_en', models.CharField(max_length=200)),
                ('label_km', models.CharField(blank=True, max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Short text'), ('email', 'Email'), ('phone', 'Phone'), ('textarea', 'Long text'), ('select', 'Select')], default='text', max_length=12)),
                ('required', models.BooleanField(default=False)),
                ('options_json', models.JSONField(blank=True, default=list)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('is_preset', models.BooleanField(default=False, help_text='Preset fields cannot be deleted.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_fields', to='events.event')),
            ],
            options={
                'ordering': ('order_index', 'field_key'),
                'constraints': [models.UniqueConstraint(fields=('event', 'field_key'), name='unique_field_key_per_event')],
            },
        ),
    ]
