# Generated by Django 5.1.15 on 2026-05-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_registrationfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='walkin_capacity',
            field=models.PositiveIntegerField(default=0, help_text='Hard cap on total walk-in guests (counting all non-voided). 0 means unlimited.'),
        ),
    ]
