# Generated by Django 5.1.15 on 2026-05-31 15:49

import apps.common.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_walkin_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, storage=apps.common.storage.public_media_storage, upload_to='event-banners/'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
