# Generated by Django 5.1.15 on 2026-06-26 08:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_banner_image_event_description'),
        ('orgs', '0002_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSlugAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_aliases', to='events.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orgs.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'slug'), name='unique_event_slug_alias_per_org')],
            },
        ),
    ]
