import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Gatethres Scanner",
    short_name: "Gatethres",
    description: "Door-day check-in for Gatethres events",
    start_url: "/scanner/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#0a0a0a",
    theme_color: "#0a0a0a",
    icons: [
      // Placeholder PNGs (192 + 512) — generated by `scripts/generate-placeholder-icons.mjs`.
      // Chrome's PWA installability heuristic requires PNG icons at both 192×192
      // and 512×512 for `beforeinstallprompt` to fire. Branded icons replace
      // these in pre-pilot QA — same file paths, no manifest change needed.
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/favicon.ico", sizes: "any", type: "image/x-icon" },
    ],
  };
}
