# Generated by Django 5.1.15 on 2026-06-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0003_auditevent_organization_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="actor_type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("scanner_device", "Scanner device"),
                    ("guest", "Guest"),
                    ("integration", "Integration"),
                    ("system", "System"),
                ],
                max_length=16,
            ),
        ),
    ]
