#!/usr/bin/env node
/**
 * Bundle sw-src/sw.ts → public/sw.js.
 *
 * Plan E originally walked `.next/static/` to build a Workbox precache
 * manifest, but that approach is incompatible with Vercel: Vercel's
 * framework detection runs `next build` only (not the chained `pnpm build`
 * in package.json), so this script never executes during deploy. The
 * committed `public/sw.js` would ship with whoever-built-it-last's chunk
 * hashes, while Vercel serves freshly-hashed chunks → `bad-precaching-response`.
 *
 * The SW now relies entirely on runtime caching (NetworkFirst for
 * `/_next/static/*`, CacheFirst for shell assets). No precache manifest
 * is baked in. This makes the SW bundle hash-stable: a given sw-src/sw.ts
 * produces the same sw.js byte-for-byte, regardless of build environment.
 */

import { build } from "esbuild";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FRONTEND_ROOT = path.resolve(__dirname, "..");
const SW_SOURCE = path.join(FRONTEND_ROOT, "sw-src", "sw.ts");
const SW_OUTPUT = path.join(FRONTEND_ROOT, "public", "sw.js");

async function main() {
  console.log("[build-sw] bundling sw-src/sw.ts (no precache manifest)");

  await build({
    entryPoints: [SW_SOURCE],
    bundle: true,
    minify: true,
    format: "iife",
    platform: "browser",
    target: "es2020",
    outfile: SW_OUTPUT,
    banner: {
      js: "// Generated by scripts/build-sw.mjs from sw-src/sw.ts — do not edit.",
    },
  });

  console.log(`[build-sw] wrote ${SW_OUTPUT}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
