#!/usr/bin/env node
/**
 * Bundle sw-src/sw.ts → public/sw.js with Workbox runtime inlined.
 *
 * Builds the Next.js static-asset manifest from .next/static/, then esbuilds
 * the SW source with __WB_MANIFEST replaced by that list. Run AFTER next build
 * (the script reads .next/static/, which is created by `next build`).
 */

import { build } from "esbuild";
import { readdir, stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FRONTEND_ROOT = path.resolve(__dirname, "..");
const NEXT_STATIC = path.join(FRONTEND_ROOT, ".next", "static");
const SW_SOURCE = path.join(FRONTEND_ROOT, "sw-src", "sw.ts");
const SW_OUTPUT = path.join(FRONTEND_ROOT, "public", "sw.js");

async function walk(dir) {
  let entries = [];
  try {
    entries = await readdir(dir);
  } catch {
    return [];
  }
  const out = [];
  for (const e of entries) {
    const full = path.join(dir, e);
    const s = await stat(full);
    if (s.isDirectory()) {
      out.push(...(await walk(full)));
    } else {
      out.push(full);
    }
  }
  return out;
}

async function buildManifest() {
  const files = await walk(NEXT_STATIC);
  return files.map((f) => ({
    url:
      "/" +
      path
        .relative(FRONTEND_ROOT, f)
        .replace(/\\/g, "/")
        .replace(/^\.next\//, "_next/"),
    revision: null, // Next.js fingerprints in the filename
  }));
}

async function main() {
  const manifest = await buildManifest();
  const manifestJson = JSON.stringify(manifest);
  console.log(`[build-sw] precaching ${manifest.length} static assets`);

  await build({
    entryPoints: [SW_SOURCE],
    bundle: true,
    minify: true,
    format: "iife",
    platform: "browser",
    target: "es2020",
    outfile: SW_OUTPUT,
    banner: {
      js: "// Generated by scripts/build-sw.mjs from sw-src/sw.ts — do not edit.",
    },
    define: {
      "self.__WB_MANIFEST": manifestJson,
    },
  });

  console.log(`[build-sw] wrote ${SW_OUTPUT}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
