#!/usr/bin/env node
/**
 * Bundle sw-src/sw.ts → public/sw.js with Workbox runtime inlined.
 *
 * Builds the Next.js static-asset manifest from .next/static/, then esbuilds
 * the SW source with __WB_MANIFEST replaced by that list. Run AFTER next build
 * (the script reads .next/static/, which is created by `next build`).
 */

import { build } from "esbuild";
import { readdir, stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FRONTEND_ROOT = path.resolve(__dirname, "..");
const NEXT_STATIC = path.join(FRONTEND_ROOT, ".next", "static");
const SW_SOURCE = path.join(FRONTEND_ROOT, "sw-src", "sw.ts");
const SW_OUTPUT = path.join(FRONTEND_ROOT, "public", "sw.js");

async function walk(dir) {
  let entries = [];
  try {
    entries = await readdir(dir);
  } catch {
    return [];
  }
  const out = [];
  for (const e of entries) {
    const full = path.join(dir, e);
    const s = await stat(full);
    if (s.isDirectory()) {
      out.push(...(await walk(full)));
    } else {
      out.push(full);
    }
  }
  return out;
}

// Next.js writes a few internal manifest files into `.next/static/<BUILD_ID>/`
// (`_buildManifest.js`, `_ssgManifest.js`, `_clientMiddlewareManifest.js`).
// These are NOT served as public static assets in production — Vercel returns
// 404 for them — so we MUST filter them out of the precache, otherwise
// Workbox throws `bad-precaching-response` on SW install.
//
// The pattern is: any underscore-prefixed `.js` directly inside the build-ID
// directory. Other files (chunks/, css/, media/) are public and must stay.
function isPublicAsset(relUnix) {
  const base = path.posix.basename(relUnix);
  const dir = path.posix.dirname(relUnix); // e.g. "_next/static/<BUILD_ID>"
  // Match files directly inside `_next/static/<single-segment>/`
  const inBuildIdDir = /^_next\/static\/[^/]+$/.test(dir);
  if (inBuildIdDir && base.startsWith("_") && base.endsWith(".js")) return false;
  return true;
}

async function buildManifest() {
  const files = await walk(NEXT_STATIC);
  const entries = files.map((f) => {
    const rel = path.relative(FRONTEND_ROOT, f).replace(/\\/g, "/");
    const url = "/" + rel.replace(/^\.next\//, "_next/");
    return { url, rel };
  });
  const kept = entries.filter((e) => isPublicAsset(e.url.replace(/^\//, "")));
  const skipped = entries.length - kept.length;
  if (skipped > 0) {
    console.log(`[build-sw] skipped ${skipped} internal Next.js manifest file(s) from precache`);
  }
  return kept.map(({ url }) => ({
    url,
    revision: null, // Next.js fingerprints in the filename
  }));
}

async function main() {
  const manifest = await buildManifest();
  const manifestJson = JSON.stringify(manifest);
  console.log(`[build-sw] precaching ${manifest.length} static assets`);

  await build({
    entryPoints: [SW_SOURCE],
    bundle: true,
    minify: true,
    format: "iife",
    platform: "browser",
    target: "es2020",
    outfile: SW_OUTPUT,
    banner: {
      js: "// Generated by scripts/build-sw.mjs from sw-src/sw.ts — do not edit.",
    },
    define: {
      "self.__WB_MANIFEST": manifestJson,
    },
  });

  console.log(`[build-sw] wrote ${SW_OUTPUT}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
