# Generated by Django 5.1.15 on 2026-05-20 13:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_registrationfield'),
        ('orgs', '0002_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_type', models.CharField(choices=[('pre_registered', 'Pre-registered'), ('walk_in', 'Walk-in')], max_length=16)),
                ('entry_token', models.CharField(max_length=128)),
                ('entry_status', models.CharField(choices=[('registered_not_arrived', 'Registered, not arrived'), ('checked_in', 'Checked in'), ('displayed', 'Walk-in displayed'), ('voided', 'Voided'), ('manual_review', 'Manual review')], default='registered_not_arrived', max_length=24)),
                ('info_status', models.CharField(choices=[('claimed_pending_info', 'Claimed, pending info'), ('info_completed', 'Info completed'), ('manual_review', 'Manual review')], default='info_completed', max_length=24)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_or_chat', models.CharField(blank=True, max_length=64)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, max_length=32)),
                ('gate', models.CharField(blank=True, max_length=64)),
                ('scanner', models.CharField(blank=True, max_length=64)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orgs.organization')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event', 'entry_status'], name='guests_gues_event_i_08a7a1_idx'), models.Index(fields=['event', 'email'], name='guests_gues_event_i_03239c_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'entry_token'), name='unique_token_per_event')],
            },
        ),
    ]
