# Generated by Django 5.1.15 on 2026-05-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_csvimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvimport',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
