# Generated by Django 5.1.15 on 2026-05-31 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_csvimport_last_error'),
        ('shorturls', '0002_shorturl_is_active_shorturl_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='referrer_short_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_guests', to='shorturls.shorturl'),
        ),
    ]
