# Generated by Django 5.1.15 on 2026-06-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_guest_referrer_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='device_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
