# Generated by Django 5.1.15 on 2026-06-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('events', '0004_event_banner_image_event_description'),
        ('orgs', '0002_invite'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scannerdevice',
            name='unique_device_label_per_event_role',
        ),
        migrations.AddConstraint(
            model_name='scannerdevice',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('event', 'label', 'role'), name='unique_active_device_label_per_event_role'),
        ),
    ]
