from django.urls import path

from apps.guests.views import (
    CsvImportCommitView,
    CsvImportPreviewView,
    CsvImportStatusView,
    GuestBulkView,
    GuestDetailView,
    GuestExportView,
    GuestListView,
    GuestQrView,
    GuestSendQrEmailView,
    GuestSyncView,
    GuestTelegramLinkView,
    GuestVoidView,
    PublicRegistrationView,
)

urlpatterns = [
    path(
        "e/<slug:org_slug>/<slug:event_slug>/register/",
        PublicRegistrationView.as_view(),
        name="public-registration",
    ),
    path(
        "orgs/<slug:org_slug>/events/<slug:event_slug>/guests/",
        GuestListView.as_view({"get": "list"}),
        name="guest-list",
    ),
    path(
        "orgs/<slug:org_slug>/events/<slug:event_slug>/guests/bulk/",
        GuestBulkView.as_view(),
        name="guest-bulk",
    ),
    path(
        "orgs/<slug:org_slug>/events/<slug:event_slug>/guests/sync/",
        GuestSyncView.as_view(),
        name="guest-sync",
    ),
    path(
        "orgs/<slug:org_slug>/events/<slug:event_slug>/guests/export/",
        GuestExportView.as_view(),
        name="guest-export",
    ),
    path(
        "orgs/<slug:org_slug>/events/<slug:event_slug>/imports/preview/",
        CsvImportPreviewView.as_view(),
        name="csv-import-preview",
    ),
    path(
        "orgs/<slug:org_slug>/events/<slug:event_slug>/imports/",
        CsvImportCommitView.as_view(),
        name="csv-import-commit",
    ),
    path(
        "orgs/<slug:org_slug>/events/<slug:event_slug>/imports/<uuid:import_id>/",
        CsvImportStatusView.as_view(),
        name="csv-import-status",
    ),
    path(
        "orgs/<slug:org_slug>/events/<slug:event_slug>/guests/<uuid:guest_id>/",
        GuestDetailView.as_view(),
        name="guest-detail",
    ),
    path(
        "orgs/<slug:org_slug>/events/<slug:event_slug>/guests/<uuid:guest_id>/void/",
        GuestVoidView.as_view(),
        name="guest-void",
    ),
    path(
        "orgs/<slug:org_slug>/events/<slug:event_slug>/guests/<uuid:guest_id>/send-qr-email/",
        GuestSendQrEmailView.as_view(),
        name="guest-send-qr-email",
    ),
    path(
        "orgs/<slug:org_slug>/events/<slug:event_slug>/guests/<uuid:guest_id>/telegram-link/",
        GuestTelegramLinkView.as_view(),
        name="guest-telegram-link",
    ),
    path("guests/<uuid:guest_id>/qr.png", GuestQrView.as_view(), name="guest-qr"),
]
