# Generated by Django 5.1.15 on 2026-06-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleformbridge',
            name='seen_labels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='googleformbridge',
            name='test_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='googleformsubmission',
            name='kind',
            field=models.CharField(choices=[('real', 'Real'), ('test', 'Test')], default='real', max_length=8),
        ),
    ]
