# Generated by Django 5.1.15 on 2026-05-21 12:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('events', '0002_registrationfield'),
        ('orgs', '0002_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDeskTicketState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_action', models.CharField(blank=True, choices=[('approve_checkin', 'Approve check-in'), ('resolved_with_note', 'Resolved with note'), ('void', 'Void')], max_length=24)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('audit_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='helpdesk_state', to='audit.auditevent')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='events.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orgs.organization')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event', 'claim_status', '-created_at'], name='hdts_event_status')],
            },
        ),
    ]
