# Generated by Django 5.1.15 on 2026-05-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_backfill_existing_escalations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpdeskticketstate',
            name='resolution_action',
            field=models.CharField(blank=True, choices=[('approve_checkin', 'Approve check-in'), ('resolved_with_note', 'Resolved with note'), ('void', 'Void'), ('escalated_to_manual_review', 'Escalated to manual review')], max_length=32),
        ),
    ]
