# Generated by Django 5.1.15 on 2026-05-21 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_registrationfield'),
        ('helpdesk', '0002_backfill_existing_escalations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpdeskticketstate',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='events.event'),
        ),
    ]
