# Generated by Django 5.1.15 on 2026-05-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_alter_helpdeskticketstate_resolution_action'),
        ('helpdesk', '0003_event_nullable'),
    ]

    operations = [
    ]
